name: Python API CI

on:
  push:
    branches:
      - main
      - recovery-branch
  pull_request:
    branches:
      - main
      - recovery-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files  
    - name: Run pre-commit hooks
      run: |
        uvicorn src.app:app --reload
 
